include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   :=  goodix_tool.o
obj-y   +=  gt9xx_driver.o
obj-y   +=  gt9xx_update.o
obj-y   +=  mtk_tpd.o
obj-y   +=  tpd_button.o
obj-y   +=  tpd_calibrate.o
obj-y   +=  tpd_debug.o
obj-y   +=  tpd_default.o
obj-y   +=  tpd_init.o
obj-y   +=  tpd_misc.o
obj-y   +=  tpd_setting.o

